# Generated by Django 5.2.5 on 2025-08-16 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('rate_limit', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='NationalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=14, unique=True)),
                ('birth_date', models.DateField()),
                ('governorate_code', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=6)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
