# Generated by Django 5.2.5 on 2025-08-16 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nid_validator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='rate_limit',
        ),
        migrations.AddField(
            model_name='apikey',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='apikey',
            name='monthly_quota',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
